{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.managedPrimaryApiKeyKey }}: {{ .Values.secret.managedPrimaryApiKey | quote }}
  {{ .Values.secret.privateVllmApiKeyKey }}: {{ .Values.secret.privateVllmApiKey | quote }}
{{- end }}

