apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

